# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shareProfileAllocator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'shareProfileAllocator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bshareProfileAllocator.proto\x12\x15shareprofileallocator\"\x16\n\x06Ticker\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x97\x06\n\tShareData\x12\x0b\n\x03\x61sk\x18\x01 \x01(\x01\x12\n\n\x02pe\x18\x02 \x01(\x01\x12\x0b\n\x03nav\x18\x03 \x01(\x01\x12\x12\n\nmarket_cap\x18\x04 \x01(\x03\x12\x0e\n\x06volume\x18\x06 \x01(\x03\x12\x0e\n\x06symbol\x18\x07 \x01(\t\x12\x16\n\x0e\x64ividend_yield\x18\x08 \x01(\x01\x12\x11\n\tlong_name\x18\t \x01(\t\x12\x1d\n\x15long_business_summary\x18\n \x01(\t\x12\x10\n\x08\x61\x64\x64ress1\x18\x0b \x01(\t\x12\x10\n\x08\x61\x64\x64ress2\x18\x0c \x01(\t\x12\x0c\n\x04\x63ity\x18\r \x01(\t\x12\r\n\x05state\x18\x0e \x01(\t\x12\x0b\n\x03zip\x18\x0f \x01(\t\x12\x0f\n\x07\x63ountry\x18\x10 \x01(\t\x12\x14\n\x0cphone_number\x18\x11 \x01(\t\x12\x0f\n\x07website\x18\x12 \x01(\t\x12\x10\n\x08industry\x18\x13 \x01(\t\x12\x0e\n\x06sector\x18\x14 \x01(\t\x12\x15\n\rexchange_name\x18\x15 \x01(\t\x12\x0e\n\x06region\x18\x16 \x01(\t\x12\x1f\n\x17num_full_time_employees\x18\x17 \x01(\x03\x12\x18\n\x10\x63ompany_officers\x18\x18 \x03(\t\x12\x15\n\rtotal_revenue\x18\x19 \x01(\x03\x12\x16\n\x0erevenue_growth\x18\x1a \x01(\x01\x12\x19\n\x11revenue_per_share\x18\x1b \x01(\x01\x12\x15\n\rgross_profits\x18\x1c \x01(\x03\x12\x16\n\x0eprofit_margins\x18\x1d \x01(\x01\x12\x12\n\ntotal_debt\x18\x1e \x01(\x03\x12\x16\n\x0e\x64\x65\x62t_to_equity\x18\x1f \x01(\x01\x12\x18\n\x10operating_margin\x18  \x01(\x01\x12\x14\n\x0cgross_margin\x18! \x01(\x01\x12\x15\n\rebitda_margin\x18\" \x01(\x01\x12\x17\n\x0f\x65\x61rnings_growth\x18# \x01(\x01\x12\x1b\n\x13operating_cash_flow\x18$ \x01(\x03\x12\x16\n\x0e\x66ree_cash_flow\x18% \x01(\x03\x12\x0e\n\x06\x65\x62itda\x18& \x01(\x03\x12\x12\n\ntotal_cash\x18\' \x01(\x03\x32\x61\n\x08ShareAPI\x12U\n\x10GetDataForTicker\x12\x1d.shareprofileallocator.Ticker\x1a .shareprofileallocator.ShareData\"\x00\x42\x1cZ\x1ainternal/grpc/generated/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shareProfileAllocator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032internal/grpc/generated/go'
  _globals['_TICKER']._serialized_start=54
  _globals['_TICKER']._serialized_end=76
  _globals['_SHAREDATA']._serialized_start=79
  _globals['_SHAREDATA']._serialized_end=870
  _globals['_SHAREAPI']._serialized_start=872
  _globals['_SHAREAPI']._serialized_end=969
# @@protoc_insertion_point(module_scope)
