# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shareProfileAllocator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'shareProfileAllocator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bshareProfileAllocator.proto\x12\x15shareprofileallocator\"\x16\n\x06Ticker\x12\x0c\n\x04name\x18\x01 \x01(\t\"e\n\tShareData\x12\x0b\n\x03\x61sk\x18\x01 \x01(\x01\x12\n\n\x02pe\x18\x02 \x01(\x01\x12\x0b\n\x03nav\x18\x03 \x01(\x01\x12\x12\n\nmarket_cap\x18\x04 \x01(\x03\x12\x0e\n\x06volume\x18\x06 \x01(\x03\x12\x0e\n\x06symbol\x18\x07 \x01(\t2a\n\x08ShareAPI\x12U\n\x10GetDataForTicker\x12\x1d.shareprofileallocator.Ticker\x1a .shareprofileallocator.ShareData\"\x00\x42\x1cZ\x1ainternal/grpc/generated/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shareProfileAllocator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032internal/grpc/generated/go'
  _globals['_TICKER']._serialized_start=54
  _globals['_TICKER']._serialized_end=76
  _globals['_SHAREDATA']._serialized_start=78
  _globals['_SHAREDATA']._serialized_end=179
  _globals['_SHAREAPI']._serialized_start=181
  _globals['_SHAREAPI']._serialized_end=278
# @@protoc_insertion_point(module_scope)
